 # COMP20003
 # Yelp Database
 # Author: <Justin Bugeja> <jbugeja> <758397>
 
CC = gcc
FILES = main.c dictionary.c
EXE = yelp1

$(EXE): $(FILES)
	$(CC) -g -o $(EXE) $(FILES)

clean: 
	rm -f *.o $(EXE)
